set nocompatible
filetype off

if has('vim_starting')
  set runtimepath+=~/dotfiles/vim/bundle/neobundle.vim
endif
call neobundle#rc(expand('~/dotfiles/vim/bundle/'))

NeoBundle 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'Shougo/neocomplcache'
NeoBundle 'Shougo/neosnippet'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimshell'

NeoBundle 'taichouchou2/alpaca_powertabline'
NeoBundle 'Lokaltog/powerline', { 'rtp' : 'powerline/bindings/vim'}

NeoBundle 'altercation/vim-colors-solarized'

syntax enable
set background=dark
colorscheme solarized
let g:solarized_termcolors = 256
let g:solarized_termtrans = 1

filetype plugin indent on
filetype indent on
syntax on

