export LANG=ja_JP.UTF-8
ANDROID_HOME=~/Library/android-sdk-macosx
PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:/usr/local/bin:/usrlocal/sbin:$PATH


# Oh-my-zsh
ZSH=$HOME/dotfiles/zsh/oh-my-zsh
ZSH_THEME="agnoster"
plugins=(git autojump brew mvn)
source $ZSH/oh-my-zsh.sh


# Aliases
alias vim='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
